"""Immutable source facts captured from native Trader SPI callbacks.

These records retain callback origin and the client state observed while the
callback was copied. They are diagnostic source facts only: an event never
binds an authorized account or trading scope.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Union

CallbackScalar = Union[str, bytes, int, float, bool, None]


@dataclass(frozen=True)
class CtpTraderCallbackSourceEvent:
    """One callback-time snapshot from a validated Trader API/SPI pair.

    ``source_sequence`` orders accepted callbacks within one client instance.
    ``raw_correlation_fields`` preserves native getter values and callback
    arguments without normalization. The API and SPI IDs are opaque tokens
    generated by the source adapter; they do not expose native objects or prove
    provider acceptance.

    The account/scope binding is intentionally fixed to ``unbound``. This
    record cannot be used as a write grant or as verifier input.
    """

    event_type: Literal["OnRtnOrder", "OnRspOrderAction", "OnErrRtnOrderAction"]
    source_instance_id: str
    native_client_epoch: str
    native_api_source_id: str
    native_spi_source_id: str
    source_sequence: int
    callback_monotonic_ns: int
    native_api_generation: int
    connection_generation: int
    login_verified: bool
    login_broker_id: str | None
    login_investor_id: str | None
    login_front: str | None
    login_trading_day: str | None
    login_front_id: int | None
    login_session_id: int | None
    callback_session_matches_login: bool | None
    raw_correlation_fields: tuple[tuple[str, CallbackScalar], ...]
    managed_session_epoch: str | None = None
    managed_session_epoch_bound: bool = False
    scope_binding: Literal["unbound"] = "unbound"
    trust_boundary: Literal["source_facts_only"] = "source_facts_only"

    def __post_init__(self) -> None:
        if self.event_type not in ("OnRtnOrder", "OnRspOrderAction", "OnErrRtnOrderAction"):
            raise ValueError("invalid Trader SPI callback type")
        if type(self.source_instance_id) is not str or not self.source_instance_id:
            raise ValueError("invalid source instance ID")
        if type(self.native_client_epoch) is not str or not self.native_client_epoch:
            raise ValueError("invalid native client epoch")
        if type(self.native_api_source_id) is not str or not self.native_api_source_id:
            raise ValueError("invalid native API source ID")
        if type(self.native_spi_source_id) is not str or not self.native_spi_source_id:
            raise ValueError("invalid native SPI source ID")
        if type(self.source_sequence) is not int or self.source_sequence <= 0:
            raise ValueError("invalid source callback sequence")
        if type(self.callback_monotonic_ns) is not int or self.callback_monotonic_ns < 0:
            raise ValueError("invalid callback monotonic timestamp")
        if type(self.native_api_generation) is not int or self.native_api_generation < 0:
            raise ValueError("invalid native API generation")
        if type(self.connection_generation) is not int or self.connection_generation < 0:
            raise ValueError("invalid connection generation")
        if type(self.login_verified) is not bool:
            raise ValueError("invalid login verification fact")
        for value in (
            self.login_broker_id,
            self.login_investor_id,
            self.login_front,
            self.login_trading_day,
        ):
            if value is not None and type(value) is not str:
                raise ValueError("login facts must contain source strings or None")
        for value in (self.login_front_id, self.login_session_id):
            if value is not None and type(value) is not int:
                raise ValueError("login session identifiers must be integers or None")
        if self.callback_session_matches_login is not None and type(
            self.callback_session_matches_login
        ) is not bool:
            raise ValueError("invalid callback/login comparison fact")
        if type(self.raw_correlation_fields) is not tuple or any(
            type(entry) is not tuple
            or len(entry) != 2
            or type(entry[0]) is not str
            or type(entry[1]) not in (str, bytes, int, float, bool, type(None))
            for entry in self.raw_correlation_fields
        ):
            raise ValueError("callback fields must contain primitive source facts only")
        if self.managed_session_epoch is not None or self.managed_session_epoch_bound is not False:
            raise ValueError("managed session epoch is not bound by the CTP source adapter")
        if self.scope_binding != "unbound":
            raise ValueError("CTP callback source events cannot bind an account or scope")
        if self.trust_boundary != "source_facts_only":
            raise ValueError("CTP callback source events are not verifier evidence")

    @property
    def stable_source_key(self) -> tuple[str, str, str, str, str, int, int, int]:
        """Return this callback's stable key within the source process."""

        return (
            "ctp-trader-callback-v1",
            self.source_instance_id,
            self.native_client_epoch,
            self.native_api_source_id,
            self.native_spi_source_id,
            self.native_api_generation,
            self.connection_generation,
            self.source_sequence,
        )

    @property
    def source_session_epoch(self) -> str:
        """Return the per-native-API source epoch, not a durable managed epoch."""

        return self.native_client_epoch

    def raw_value(self, name: str) -> CallbackScalar | None:
        """Return a captured value by exact field/argument name, if present."""

        return next(
            (value for field_name, value in self.raw_correlation_fields if field_name == name),
            None,
        )

    @property
    def native_correlation_key(self) -> tuple[CallbackScalar, ...]:
        """Return exact CTP sequence/request/action identifiers when present."""

        return (
            self.event_type,
            self.raw_value("SequenceNo"),
            self.raw_value("NotifySequence"),
            self.raw_value("nRequestID"),
            self.raw_value("RequestID"),
            self.raw_value("OrderActionRef"),
            self.raw_value("OrderRef"),
            self.raw_value("ExchangeID"),
            self.raw_value("OrderSysID"),
            self.raw_value("FrontID"),
            self.raw_value("SessionID"),
        )


def snapshot_exact_fields(
    field_value: object | None,
    names: tuple[str, ...],
) -> tuple[tuple[str, CallbackScalar], ...]:
    """Copy selected SWIG getters as primitive values, preserving them raw."""

    if field_value is None:
        return ()

    captured: list[tuple[str, CallbackScalar]] = []
    for name in names:
        try:
            value = getattr(field_value, name)
        except Exception:
            continue
        if type(value) not in (str, bytes, int, float, bool, type(None)):
            continue
        captured.append((name, value))
    return tuple(captured)


__all__ = ["CtpTraderCallbackSourceEvent"]
