# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP  API (CThostFtdcTraderSpi / CThostFtdcTraderApi)"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr, print_exception, stderr, weakref


class CThostFtdcTraderSpi:
    """Class CThostFtdcTraderSpi"""
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag'
    )
    __repr__ = _swig_repr

    def OnFrontConnected(self):
        """OnFrontConnected method"""
        return _ctp.CThostFtdcTraderSpi_OnFrontConnected(self)

    def OnFrontDisconnected(self, nReason):
        """OnFrontDisconnected method"""
        return _ctp.CThostFtdcTraderSpi_OnFrontDisconnected(self, nReason)

    def OnHeartBeatWarning(self, nTimeLapse):
        """OnHeartBeatWarning method"""
        return _ctp.CThostFtdcTraderSpi_OnHeartBeatWarning(self, nTimeLapse)

    def OnRspAuthenticate(self, pRspAuthenticateField, pRspInfo, nRequestID, bIsLast):
        """OnRspAuthenticate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspAuthenticate(
            self, pRspAuthenticateField, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUserLogin(self, pRspUserLogin, pRspInfo, nRequestID, bIsLast):
        """OnRspUserLogin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspUserLogin(
            self, pRspUserLogin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUserLogout(self, pUserLogout, pRspInfo, nRequestID, bIsLast):
        """OnRspUserLogout method"""
        return _ctp.CThostFtdcTraderSpi_OnRspUserLogout(
            self, pUserLogout, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUserPasswordUpdate(
        self, pUserPasswordUpdate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspUserPasswordUpdate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspUserPasswordUpdate(
            self, pUserPasswordUpdate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspTradingAccountPasswordUpdate(
        self, pTradingAccountPasswordUpdate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspTradingAccountPasswordUpdate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspTradingAccountPasswordUpdate(
            self, pTradingAccountPasswordUpdate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUserAuthMethod(self, pRspUserAuthMethod, pRspInfo, nRequestID, bIsLast):
        """OnRspUserAuthMethod method"""
        return _ctp.CThostFtdcTraderSpi_OnRspUserAuthMethod(
            self, pRspUserAuthMethod, pRspInfo, nRequestID, bIsLast
        )

    def OnRspGenUserCaptcha(self, pRspGenUserCaptcha, pRspInfo, nRequestID, bIsLast):
        """OnRspGenUserCaptcha method"""
        return _ctp.CThostFtdcTraderSpi_OnRspGenUserCaptcha(
            self, pRspGenUserCaptcha, pRspInfo, nRequestID, bIsLast
        )

    def OnRspGenUserText(self, pRspGenUserText, pRspInfo, nRequestID, bIsLast):
        """OnRspGenUserText method"""
        return _ctp.CThostFtdcTraderSpi_OnRspGenUserText(
            self, pRspGenUserText, pRspInfo, nRequestID, bIsLast
        )

    def OnRspOrderInsert(self, pInputOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspOrderInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspOrderInsert(
            self, pInputOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspParkedOrderInsert(self, pParkedOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspParkedOrderInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspParkedOrderInsert(
            self, pParkedOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspParkedOrderAction(self, pParkedOrderAction, pRspInfo, nRequestID, bIsLast):
        """OnRspParkedOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspParkedOrderAction(
            self, pParkedOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspOrderAction(self, pInputOrderAction, pRspInfo, nRequestID, bIsLast):
        """OnRspOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspOrderAction(
            self, pInputOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryMaxOrderVolume(self, pQryMaxOrderVolume, pRspInfo, nRequestID, bIsLast):
        """OnRspQryMaxOrderVolume method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryMaxOrderVolume(
            self, pQryMaxOrderVolume, pRspInfo, nRequestID, bIsLast
        )

    def OnRspSettlementInfoConfirm(
        self, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspSettlementInfoConfirm method"""
        return _ctp.CThostFtdcTraderSpi_OnRspSettlementInfoConfirm(
            self, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast
        )

    def OnRspRemoveParkedOrder(self, pRemoveParkedOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspRemoveParkedOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRspRemoveParkedOrder(
            self, pRemoveParkedOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspRemoveParkedOrderAction(
        self, pRemoveParkedOrderAction, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspRemoveParkedOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspRemoveParkedOrderAction(
            self, pRemoveParkedOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspExecOrderInsert(self, pInputExecOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspExecOrderInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspExecOrderInsert(
            self, pInputExecOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspExecOrderAction(
        self, pInputExecOrderAction, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspExecOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspExecOrderAction(
            self, pInputExecOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspForQuoteInsert(self, pInputForQuote, pRspInfo, nRequestID, bIsLast):
        """OnRspForQuoteInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspForQuoteInsert(
            self, pInputForQuote, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQuoteInsert(self, pInputQuote, pRspInfo, nRequestID, bIsLast):
        """OnRspQuoteInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQuoteInsert(
            self, pInputQuote, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQuoteAction(self, pInputQuoteAction, pRspInfo, nRequestID, bIsLast):
        """OnRspQuoteAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQuoteAction(
            self, pInputQuoteAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspBatchOrderAction(
        self, pInputBatchOrderAction, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspBatchOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspBatchOrderAction(
            self, pInputBatchOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspOptionSelfCloseInsert(
        self, pInputOptionSelfClose, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspOptionSelfCloseInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspOptionSelfCloseInsert(
            self, pInputOptionSelfClose, pRspInfo, nRequestID, bIsLast
        )

    def OnRspOptionSelfCloseAction(
        self, pInputOptionSelfCloseAction, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspOptionSelfCloseAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspOptionSelfCloseAction(
            self, pInputOptionSelfCloseAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspCombActionInsert(self, pInputCombAction, pRspInfo, nRequestID, bIsLast):
        """OnRspCombActionInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnRspCombActionInsert(
            self, pInputCombAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryOrder(self, pOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspQryOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryOrder(
            self, pOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTrade(self, pTrade, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTrade method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTrade(
            self, pTrade, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorPosition(
        self, pInvestorPosition, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorPosition method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorPosition(
            self, pInvestorPosition, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTradingAccount(self, pTradingAccount, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTradingAccount method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTradingAccount(
            self, pTradingAccount, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestor(self, pInvestor, pRspInfo, nRequestID, bIsLast):
        """OnRspQryInvestor method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestor(
            self, pInvestor, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTradingCode(self, pTradingCode, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTradingCode method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTradingCode(
            self, pTradingCode, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInstrumentMarginRate(
        self, pInstrumentMarginRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInstrumentMarginRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInstrumentMarginRate(
            self, pInstrumentMarginRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInstrumentCommissionRate(
        self, pInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInstrumentCommissionRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInstrumentCommissionRate(
            self, pInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryExchange(self, pExchange, pRspInfo, nRequestID, bIsLast):
        """OnRspQryExchange method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryExchange(
            self, pExchange, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryProduct(self, pProduct, pRspInfo, nRequestID, bIsLast):
        """OnRspQryProduct method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryProduct(
            self, pProduct, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInstrument(self, pInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspQryInstrument method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInstrument(
            self, pInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryDepthMarketData(self, pDepthMarketData, pRspInfo, nRequestID, bIsLast):
        """OnRspQryDepthMarketData method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryDepthMarketData(
            self, pDepthMarketData, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTraderOffer(self, pTraderOffer, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTraderOffer method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTraderOffer(
            self, pTraderOffer, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySettlementInfo(self, pSettlementInfo, pRspInfo, nRequestID, bIsLast):
        """OnRspQrySettlementInfo method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySettlementInfo(
            self, pSettlementInfo, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTransferBank(self, pTransferBank, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTransferBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTransferBank(
            self, pTransferBank, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorPositionDetail(
        self, pInvestorPositionDetail, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorPositionDetail method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorPositionDetail(
            self, pInvestorPositionDetail, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryNotice(self, pNotice, pRspInfo, nRequestID, bIsLast):
        """OnRspQryNotice method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryNotice(
            self, pNotice, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySettlementInfoConfirm(
        self, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySettlementInfoConfirm method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySettlementInfoConfirm(
            self, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorPositionCombineDetail(
        self, pInvestorPositionCombineDetail, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorPositionCombineDetail method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorPositionCombineDetail(
            self, pInvestorPositionCombineDetail, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryCFMMCTradingAccountKey(
        self, pCFMMCTradingAccountKey, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryCFMMCTradingAccountKey method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryCFMMCTradingAccountKey(
            self, pCFMMCTradingAccountKey, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryEWarrantOffset(self, pEWarrantOffset, pRspInfo, nRequestID, bIsLast):
        """OnRspQryEWarrantOffset method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryEWarrantOffset(
            self, pEWarrantOffset, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorProductGroupMargin(
        self, pInvestorProductGroupMargin, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorProductGroupMargin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorProductGroupMargin(
            self, pInvestorProductGroupMargin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryExchangeMarginRate(
        self, pExchangeMarginRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryExchangeMarginRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryExchangeMarginRate(
            self, pExchangeMarginRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryExchangeMarginRateAdjust(
        self, pExchangeMarginRateAdjust, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryExchangeMarginRateAdjust method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryExchangeMarginRateAdjust(
            self, pExchangeMarginRateAdjust, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryExchangeRate(self, pExchangeRate, pRspInfo, nRequestID, bIsLast):
        """OnRspQryExchangeRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryExchangeRate(
            self, pExchangeRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySecAgentACIDMap(self, pSecAgentACIDMap, pRspInfo, nRequestID, bIsLast):
        """OnRspQrySecAgentACIDMap method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySecAgentACIDMap(
            self, pSecAgentACIDMap, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryProductExchRate(self, pProductExchRate, pRspInfo, nRequestID, bIsLast):
        """OnRspQryProductExchRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryProductExchRate(
            self, pProductExchRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryProductGroup(self, pProductGroup, pRspInfo, nRequestID, bIsLast):
        """OnRspQryProductGroup method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryProductGroup(
            self, pProductGroup, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryMMInstrumentCommissionRate(
        self, pMMInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryMMInstrumentCommissionRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryMMInstrumentCommissionRate(
            self, pMMInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryMMOptionInstrCommRate(
        self, pMMOptionInstrCommRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryMMOptionInstrCommRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryMMOptionInstrCommRate(
            self, pMMOptionInstrCommRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInstrumentOrderCommRate(
        self, pInstrumentOrderCommRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInstrumentOrderCommRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInstrumentOrderCommRate(
            self, pInstrumentOrderCommRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySecAgentTradingAccount(
        self, pTradingAccount, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySecAgentTradingAccount method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySecAgentTradingAccount(
            self, pTradingAccount, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySecAgentCheckMode(
        self, pSecAgentCheckMode, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySecAgentCheckMode method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySecAgentCheckMode(
            self, pSecAgentCheckMode, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySecAgentTradeInfo(
        self, pSecAgentTradeInfo, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySecAgentTradeInfo method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySecAgentTradeInfo(
            self, pSecAgentTradeInfo, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryOptionInstrTradeCost(
        self, pOptionInstrTradeCost, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryOptionInstrTradeCost method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryOptionInstrTradeCost(
            self, pOptionInstrTradeCost, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryOptionInstrCommRate(
        self, pOptionInstrCommRate, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryOptionInstrCommRate method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryOptionInstrCommRate(
            self, pOptionInstrCommRate, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryExecOrder(self, pExecOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspQryExecOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryExecOrder(
            self, pExecOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryForQuote(self, pForQuote, pRspInfo, nRequestID, bIsLast):
        """OnRspQryForQuote method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryForQuote(
            self, pForQuote, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryQuote(self, pQuote, pRspInfo, nRequestID, bIsLast):
        """OnRspQryQuote method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryQuote(
            self, pQuote, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryOptionSelfClose(self, pOptionSelfClose, pRspInfo, nRequestID, bIsLast):
        """OnRspQryOptionSelfClose method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryOptionSelfClose(
            self, pOptionSelfClose, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestUnit(self, pInvestUnit, pRspInfo, nRequestID, bIsLast):
        """OnRspQryInvestUnit method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestUnit(
            self, pInvestUnit, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryCombInstrumentGuard(
        self, pCombInstrumentGuard, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryCombInstrumentGuard method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryCombInstrumentGuard(
            self, pCombInstrumentGuard, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryCombAction(self, pCombAction, pRspInfo, nRequestID, bIsLast):
        """OnRspQryCombAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryCombAction(
            self, pCombAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTransferSerial(self, pTransferSerial, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTransferSerial method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTransferSerial(
            self, pTransferSerial, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryAccountregister(self, pAccountregister, pRspInfo, nRequestID, bIsLast):
        """OnRspQryAccountregister method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryAccountregister(
            self, pAccountregister, pRspInfo, nRequestID, bIsLast
        )

    def OnRspError(self, pRspInfo, nRequestID, bIsLast):
        """OnRspError method"""
        return _ctp.CThostFtdcTraderSpi_OnRspError(self, pRspInfo, nRequestID, bIsLast)

    def OnRtnOrder(self, pOrder):
        """OnRtnOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnOrder(self, pOrder)

    def OnRtnTrade(self, pTrade):
        """OnRtnTrade method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnTrade(self, pTrade)

    def OnErrRtnOrderInsert(self, pInputOrder, pRspInfo):
        """OnErrRtnOrderInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnOrderInsert(self, pInputOrder, pRspInfo)

    def OnErrRtnOrderAction(self, pOrderAction, pRspInfo):
        """OnErrRtnOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnOrderAction(
            self, pOrderAction, pRspInfo
        )

    def OnRtnInstrumentStatus(self, pInstrumentStatus):
        """OnRtnInstrumentStatus method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnInstrumentStatus(self, pInstrumentStatus)

    def OnRtnBulletin(self, pBulletin):
        """OnRtnBulletin method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnBulletin(self, pBulletin)

    def OnRtnTradingNotice(self, pTradingNoticeInfo):
        """OnRtnTradingNotice method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnTradingNotice(self, pTradingNoticeInfo)

    def OnRtnErrorConditionalOrder(self, pErrorConditionalOrder):
        """OnRtnErrorConditionalOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnErrorConditionalOrder(
            self, pErrorConditionalOrder
        )

    def OnRtnExecOrder(self, pExecOrder):
        """OnRtnExecOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnExecOrder(self, pExecOrder)

    def OnErrRtnExecOrderInsert(self, pInputExecOrder, pRspInfo):
        """OnErrRtnExecOrderInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnExecOrderInsert(
            self, pInputExecOrder, pRspInfo
        )

    def OnErrRtnExecOrderAction(self, pExecOrderAction, pRspInfo):
        """OnErrRtnExecOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnExecOrderAction(
            self, pExecOrderAction, pRspInfo
        )

    def OnErrRtnForQuoteInsert(self, pInputForQuote, pRspInfo):
        """OnErrRtnForQuoteInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnForQuoteInsert(
            self, pInputForQuote, pRspInfo
        )

    def OnRtnQuote(self, pQuote):
        """OnRtnQuote method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnQuote(self, pQuote)

    def OnErrRtnQuoteInsert(self, pInputQuote, pRspInfo):
        """OnErrRtnQuoteInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnQuoteInsert(self, pInputQuote, pRspInfo)

    def OnErrRtnQuoteAction(self, pQuoteAction, pRspInfo):
        """OnErrRtnQuoteAction method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnQuoteAction(
            self, pQuoteAction, pRspInfo
        )

    def OnRtnForQuoteRsp(self, pForQuoteRsp):
        """OnRtnForQuoteRsp method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnForQuoteRsp(self, pForQuoteRsp)

    def OnRtnCFMMCTradingAccountToken(self, pCFMMCTradingAccountToken):
        """OnRtnCFMMCTradingAccountToken method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnCFMMCTradingAccountToken(
            self, pCFMMCTradingAccountToken
        )

    def OnErrRtnBatchOrderAction(self, pBatchOrderAction, pRspInfo):
        """OnErrRtnBatchOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnBatchOrderAction(
            self, pBatchOrderAction, pRspInfo
        )

    def OnRtnOptionSelfClose(self, pOptionSelfClose):
        """OnRtnOptionSelfClose method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnOptionSelfClose(self, pOptionSelfClose)

    def OnErrRtnOptionSelfCloseInsert(self, pInputOptionSelfClose, pRspInfo):
        """OnErrRtnOptionSelfCloseInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnOptionSelfCloseInsert(
            self, pInputOptionSelfClose, pRspInfo
        )

    def OnErrRtnOptionSelfCloseAction(self, pOptionSelfCloseAction, pRspInfo):
        """OnErrRtnOptionSelfCloseAction method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnOptionSelfCloseAction(
            self, pOptionSelfCloseAction, pRspInfo
        )

    def OnRtnCombAction(self, pCombAction):
        """OnRtnCombAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnCombAction(self, pCombAction)

    def OnErrRtnCombActionInsert(self, pInputCombAction, pRspInfo):
        """OnErrRtnCombActionInsert method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnCombActionInsert(
            self, pInputCombAction, pRspInfo
        )

    def OnRspQryContractBank(self, pContractBank, pRspInfo, nRequestID, bIsLast):
        """OnRspQryContractBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryContractBank(
            self, pContractBank, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryParkedOrder(self, pParkedOrder, pRspInfo, nRequestID, bIsLast):
        """OnRspQryParkedOrder method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryParkedOrder(
            self, pParkedOrder, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryParkedOrderAction(
        self, pParkedOrderAction, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryParkedOrderAction method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryParkedOrderAction(
            self, pParkedOrderAction, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryTradingNotice(self, pTradingNotice, pRspInfo, nRequestID, bIsLast):
        """OnRspQryTradingNotice method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryTradingNotice(
            self, pTradingNotice, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryBrokerTradingParams(
        self, pBrokerTradingParams, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryBrokerTradingParams method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryBrokerTradingParams(
            self, pBrokerTradingParams, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryBrokerTradingAlgos(
        self, pBrokerTradingAlgos, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryBrokerTradingAlgos method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryBrokerTradingAlgos(
            self, pBrokerTradingAlgos, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQueryCFMMCTradingAccountToken(
        self, pQueryCFMMCTradingAccountToken, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQueryCFMMCTradingAccountToken method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQueryCFMMCTradingAccountToken(
            self, pQueryCFMMCTradingAccountToken, pRspInfo, nRequestID, bIsLast
        )

    def OnRtnFromBankToFutureByBank(self, pRspTransfer):
        """OnRtnFromBankToFutureByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnFromBankToFutureByBank(self, pRspTransfer)

    def OnRtnFromFutureToBankByBank(self, pRspTransfer):
        """OnRtnFromFutureToBankByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnFromFutureToBankByBank(self, pRspTransfer)

    def OnRtnRepealFromBankToFutureByBank(self, pRspRepeal):
        """OnRtnRepealFromBankToFutureByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByBank(
            self, pRspRepeal
        )

    def OnRtnRepealFromFutureToBankByBank(self, pRspRepeal):
        """OnRtnRepealFromFutureToBankByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByBank(
            self, pRspRepeal
        )

    def OnRtnFromBankToFutureByFuture(self, pRspTransfer):
        """OnRtnFromBankToFutureByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnFromBankToFutureByFuture(
            self, pRspTransfer
        )

    def OnRtnFromFutureToBankByFuture(self, pRspTransfer):
        """OnRtnFromFutureToBankByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnFromFutureToBankByFuture(
            self, pRspTransfer
        )

    def OnRtnRepealFromBankToFutureByFutureManual(self, pRspRepeal):
        """OnRtnRepealFromBankToFutureByFutureManual method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFutureManual(
            self, pRspRepeal
        )

    def OnRtnRepealFromFutureToBankByFutureManual(self, pRspRepeal):
        """OnRtnRepealFromFutureToBankByFutureManual method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFutureManual(
            self, pRspRepeal
        )

    def OnRtnQueryBankBalanceByFuture(self, pNotifyQueryAccount):
        """OnRtnQueryBankBalanceByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnQueryBankBalanceByFuture(
            self, pNotifyQueryAccount
        )

    def OnErrRtnBankToFutureByFuture(self, pReqTransfer, pRspInfo):
        """OnErrRtnBankToFutureByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnBankToFutureByFuture(
            self, pReqTransfer, pRspInfo
        )

    def OnErrRtnFutureToBankByFuture(self, pReqTransfer, pRspInfo):
        """OnErrRtnFutureToBankByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnFutureToBankByFuture(
            self, pReqTransfer, pRspInfo
        )

    def OnErrRtnRepealBankToFutureByFutureManual(self, pReqRepeal, pRspInfo):
        """OnErrRtnRepealBankToFutureByFutureManual method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnRepealBankToFutureByFutureManual(
            self, pReqRepeal, pRspInfo
        )

    def OnErrRtnRepealFutureToBankByFutureManual(self, pReqRepeal, pRspInfo):
        """OnErrRtnRepealFutureToBankByFutureManual method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnRepealFutureToBankByFutureManual(
            self, pReqRepeal, pRspInfo
        )

    def OnErrRtnQueryBankBalanceByFuture(self, pReqQueryAccount, pRspInfo):
        """OnErrRtnQueryBankBalanceByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnErrRtnQueryBankBalanceByFuture(
            self, pReqQueryAccount, pRspInfo
        )

    def OnRtnRepealFromBankToFutureByFuture(self, pRspRepeal):
        """OnRtnRepealFromBankToFutureByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFuture(
            self, pRspRepeal
        )

    def OnRtnRepealFromFutureToBankByFuture(self, pRspRepeal):
        """OnRtnRepealFromFutureToBankByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFuture(
            self, pRspRepeal
        )

    def OnRspFromBankToFutureByFuture(
        self, pReqTransfer, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspFromBankToFutureByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRspFromBankToFutureByFuture(
            self, pReqTransfer, pRspInfo, nRequestID, bIsLast
        )

    def OnRspFromFutureToBankByFuture(
        self, pReqTransfer, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspFromFutureToBankByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRspFromFutureToBankByFuture(
            self, pReqTransfer, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQueryBankAccountMoneyByFuture(
        self, pReqQueryAccount, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQueryBankAccountMoneyByFuture method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQueryBankAccountMoneyByFuture(
            self, pReqQueryAccount, pRspInfo, nRequestID, bIsLast
        )

    def OnRtnOpenAccountByBank(self, pOpenAccount):
        """OnRtnOpenAccountByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnOpenAccountByBank(self, pOpenAccount)

    def OnRtnCancelAccountByBank(self, pCancelAccount):
        """OnRtnCancelAccountByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnCancelAccountByBank(self, pCancelAccount)

    def OnRtnChangeAccountByBank(self, pChangeAccount):
        """OnRtnChangeAccountByBank method"""
        return _ctp.CThostFtdcTraderSpi_OnRtnChangeAccountByBank(self, pChangeAccount)

    def OnRspQryClassifiedInstrument(self, pInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspQryClassifiedInstrument method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryClassifiedInstrument(
            self, pInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryCombPromotionParam(
        self, pCombPromotionParam, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryCombPromotionParam method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryCombPromotionParam(
            self, pCombPromotionParam, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRiskSettleInvstPosition(
        self, pRiskSettleInvstPosition, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRiskSettleInvstPosition method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRiskSettleInvstPosition(
            self, pRiskSettleInvstPosition, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRiskSettleProductStatus(
        self, pRiskSettleProductStatus, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRiskSettleProductStatus method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRiskSettleProductStatus(
            self, pRiskSettleProductStatus, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMFutureParameter(
        self, pSPBMFutureParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMFutureParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMFutureParameter(
            self, pSPBMFutureParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMOptionParameter(
        self, pSPBMOptionParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMOptionParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMOptionParameter(
            self, pSPBMOptionParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMIntraParameter(
        self, pSPBMIntraParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMIntraParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMIntraParameter(
            self, pSPBMIntraParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMInterParameter(
        self, pSPBMInterParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMInterParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMInterParameter(
            self, pSPBMInterParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMPortfDefinition(
        self, pSPBMPortfDefinition, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMPortfDefinition method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMPortfDefinition(
            self, pSPBMPortfDefinition, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMInvestorPortfDef(
        self, pSPBMInvestorPortfDef, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMInvestorPortfDef method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMInvestorPortfDef(
            self, pSPBMInvestorPortfDef, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorPortfMarginRatio(
        self, pInvestorPortfMarginRatio, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorPortfMarginRatio method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorPortfMarginRatio(
            self, pInvestorPortfMarginRatio, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorProdSPBMDetail(
        self, pInvestorProdSPBMDetail, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorProdSPBMDetail method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorProdSPBMDetail(
            self, pInvestorProdSPBMDetail, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorCommoditySPMMMargin(
        self, pInvestorCommoditySPMMMargin, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorCommoditySPMMMargin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorCommoditySPMMMargin(
            self, pInvestorCommoditySPMMMargin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorCommodityGroupSPMMMargin(
        self, pInvestorCommodityGroupSPMMMargin, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorCommodityGroupSPMMMargin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorCommodityGroupSPMMMargin(
            self, pInvestorCommodityGroupSPMMMargin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPMMInstParam(self, pSPMMInstParam, pRspInfo, nRequestID, bIsLast):
        """OnRspQrySPMMInstParam method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPMMInstParam(
            self, pSPMMInstParam, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPMMProductParam(
        self, pSPMMProductParam, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPMMProductParam method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPMMProductParam(
            self, pSPMMProductParam, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQrySPBMAddOnInterParameter(
        self, pSPBMAddOnInterParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQrySPBMAddOnInterParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQrySPBMAddOnInterParameter(
            self, pSPBMAddOnInterParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSCombProductInfo(
        self, pRCAMSCombProductInfo, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSCombProductInfo method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSCombProductInfo(
            self, pRCAMSCombProductInfo, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSInstrParameter(
        self, pRCAMSInstrParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSInstrParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSInstrParameter(
            self, pRCAMSInstrParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSIntraParameter(
        self, pRCAMSIntraParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSIntraParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSIntraParameter(
            self, pRCAMSIntraParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSInterParameter(
        self, pRCAMSInterParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSInterParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSInterParameter(
            self, pRCAMSInterParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSShortOptAdjustParam(
        self, pRCAMSShortOptAdjustParam, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSShortOptAdjustParam method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSShortOptAdjustParam(
            self, pRCAMSShortOptAdjustParam, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRCAMSInvestorCombPosition(
        self, pRCAMSInvestorCombPosition, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRCAMSInvestorCombPosition method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRCAMSInvestorCombPosition(
            self, pRCAMSInvestorCombPosition, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorProdRCAMSMargin(
        self, pInvestorProdRCAMSMargin, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorProdRCAMSMargin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorProdRCAMSMargin(
            self, pInvestorProdRCAMSMargin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRULEInstrParameter(
        self, pRULEInstrParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRULEInstrParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRULEInstrParameter(
            self, pRULEInstrParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRULEIntraParameter(
        self, pRULEIntraParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRULEIntraParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRULEIntraParameter(
            self, pRULEIntraParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryRULEInterParameter(
        self, pRULEInterParameter, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryRULEInterParameter method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryRULEInterParameter(
            self, pRULEInterParameter, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorProdRULEMargin(
        self, pInvestorProdRULEMargin, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorProdRULEMargin method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorProdRULEMargin(
            self, pInvestorProdRULEMargin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryInvestorPortfSetting(
        self, pInvestorPortfSetting, pRspInfo, nRequestID, bIsLast
    ):
        """OnRspQryInvestorPortfSetting method"""
        return _ctp.CThostFtdcTraderSpi_OnRspQryInvestorPortfSetting(
            self, pInvestorPortfSetting, pRspInfo, nRequestID, bIsLast
        )

    def pyError(self, type, value, traceback):
        """Handles an error thrown during invocation of an method.

        Arguments are those provided by sys.exc_info()
        """
        stderr.write('Exception thrown during method dispatch:\n')
        print_exception(type, value, traceback)

    def __init__(self):
        """__init__ method"""
        _self = None if self.__class__ == CThostFtdcTraderSpi else self
        _ctp.CThostFtdcTraderSpi_swiginit(
            self,
            _ctp.new_CThostFtdcTraderSpi(
                _self,
            ),
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcTraderSpi

    def __disown__(self):
        self.this.disown()
        _ctp.disown_CThostFtdcTraderSpi(self)
        return weakref.proxy(self)


# Register CThostFtdcTraderSpi in _ctp:
_ctp.CThostFtdcTraderSpi_swigregister(CThostFtdcTraderSpi)


class CThostFtdcTraderApi:
    """Class CThostFtdcTraderApi"""
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag'
    )

    def __init__(self, *args, **kwargs):
        """__init__ method"""
        raise AttributeError('No constructor defined - class is abstract')

    __repr__ = _swig_repr

    @staticmethod
    def CreateFtdcTraderApi(*args):
        """CreateFtdcTraderApi method"""
        return _ctp.CThostFtdcTraderApi_CreateFtdcTraderApi(*args)

    @staticmethod
    def GetApiVersion():
        """GetApiVersion method"""
        return _ctp.CThostFtdcTraderApi_GetApiVersion()

    def Release(self):
        """Release method"""
        return _ctp.CThostFtdcTraderApi_Release(self)

    def Init(self):
        """Init method"""
        return _ctp.CThostFtdcTraderApi_Init(self)

    def Join(self):
        """Join method"""
        return _ctp.CThostFtdcTraderApi_Join(self)

    def GetTradingDay(self):
        """GetTradingDay method"""
        return _ctp.CThostFtdcTraderApi_GetTradingDay(self)

    def GetFrontInfo(self, pFrontInfo):
        """GetFrontInfo method"""
        return _ctp.CThostFtdcTraderApi_GetFrontInfo(self, pFrontInfo)

    def RegisterFront(self, pszFrontAddress):
        """RegisterFront method"""
        return _ctp.CThostFtdcTraderApi_RegisterFront(self, pszFrontAddress)

    def RegisterNameServer(self, pszNsAddress):
        """RegisterNameServer method"""
        return _ctp.CThostFtdcTraderApi_RegisterNameServer(self, pszNsAddress)

    def RegisterFensUserInfo(self, pFensUserInfo):
        """RegisterFensUserInfo method"""
        return _ctp.CThostFtdcTraderApi_RegisterFensUserInfo(self, pFensUserInfo)

    def RegisterSpi(self, pSpi):
        """RegisterSpi method"""
        return _ctp.CThostFtdcTraderApi_RegisterSpi(self, pSpi)

    def SubscribePrivateTopic(self, nResumeType):
        """SubscribePrivateTopic method"""
        return _ctp.CThostFtdcTraderApi_SubscribePrivateTopic(self, nResumeType)

    def SubscribePublicTopic(self, nResumeType):
        """SubscribePublicTopic method"""
        return _ctp.CThostFtdcTraderApi_SubscribePublicTopic(self, nResumeType)

    def ReqAuthenticate(self, pReqAuthenticateField, nRequestID):
        """ReqAuthenticate method"""
        return _ctp.CThostFtdcTraderApi_ReqAuthenticate(
            self, pReqAuthenticateField, nRequestID
        )

    def RegisterUserSystemInfo(self, pUserSystemInfo):
        """RegisterUserSystemInfo method"""
        return _ctp.CThostFtdcTraderApi_RegisterUserSystemInfo(self, pUserSystemInfo)

    def SubmitUserSystemInfo(self, pUserSystemInfo):
        """SubmitUserSystemInfo method"""
        return _ctp.CThostFtdcTraderApi_SubmitUserSystemInfo(self, pUserSystemInfo)

    def ReqUserLogin(self, pReqUserLoginField, nRequestID):
        """ReqUserLogin method"""
        return _ctp.CThostFtdcTraderApi_ReqUserLogin(
            self, pReqUserLoginField, nRequestID
        )

    def ReqUserLogout(self, pUserLogout, nRequestID):
        """ReqUserLogout method"""
        return _ctp.CThostFtdcTraderApi_ReqUserLogout(self, pUserLogout, nRequestID)

    def ReqUserPasswordUpdate(self, pUserPasswordUpdate, nRequestID):
        """ReqUserPasswordUpdate method"""
        return _ctp.CThostFtdcTraderApi_ReqUserPasswordUpdate(
            self, pUserPasswordUpdate, nRequestID
        )

    def ReqTradingAccountPasswordUpdate(
        self, pTradingAccountPasswordUpdate, nRequestID
    ):
        """ReqTradingAccountPasswordUpdate method"""
        return _ctp.CThostFtdcTraderApi_ReqTradingAccountPasswordUpdate(
            self, pTradingAccountPasswordUpdate, nRequestID
        )

    def ReqUserAuthMethod(self, pReqUserAuthMethod, nRequestID):
        """ReqUserAuthMethod method"""
        return _ctp.CThostFtdcTraderApi_ReqUserAuthMethod(
            self, pReqUserAuthMethod, nRequestID
        )

    def ReqGenUserCaptcha(self, pReqGenUserCaptcha, nRequestID):
        """ReqGenUserCaptcha method"""
        return _ctp.CThostFtdcTraderApi_ReqGenUserCaptcha(
            self, pReqGenUserCaptcha, nRequestID
        )

    def ReqGenUserText(self, pReqGenUserText, nRequestID):
        """ReqGenUserText method"""
        return _ctp.CThostFtdcTraderApi_ReqGenUserText(
            self, pReqGenUserText, nRequestID
        )

    def ReqUserLoginWithCaptcha(self, pReqUserLoginWithCaptcha, nRequestID):
        """ReqUserLoginWithCaptcha method"""
        return _ctp.CThostFtdcTraderApi_ReqUserLoginWithCaptcha(
            self, pReqUserLoginWithCaptcha, nRequestID
        )

    def ReqUserLoginWithText(self, pReqUserLoginWithText, nRequestID):
        """ReqUserLoginWithText method"""
        return _ctp.CThostFtdcTraderApi_ReqUserLoginWithText(
            self, pReqUserLoginWithText, nRequestID
        )

    def ReqUserLoginWithOTP(self, pReqUserLoginWithOTP, nRequestID):
        """ReqUserLoginWithOTP method"""
        return _ctp.CThostFtdcTraderApi_ReqUserLoginWithOTP(
            self, pReqUserLoginWithOTP, nRequestID
        )

    def ReqOrderInsert(self, pInputOrder, nRequestID):
        """ReqOrderInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqOrderInsert(self, pInputOrder, nRequestID)

    def ReqParkedOrderInsert(self, pParkedOrder, nRequestID):
        """ReqParkedOrderInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqParkedOrderInsert(
            self, pParkedOrder, nRequestID
        )

    def ReqParkedOrderAction(self, pParkedOrderAction, nRequestID):
        """ReqParkedOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqParkedOrderAction(
            self, pParkedOrderAction, nRequestID
        )

    def ReqOrderAction(self, pInputOrderAction, nRequestID):
        """ReqOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqOrderAction(
            self, pInputOrderAction, nRequestID
        )

    def ReqQryMaxOrderVolume(self, pQryMaxOrderVolume, nRequestID):
        """ReqQryMaxOrderVolume method"""
        return _ctp.CThostFtdcTraderApi_ReqQryMaxOrderVolume(
            self, pQryMaxOrderVolume, nRequestID
        )

    def ReqSettlementInfoConfirm(self, pSettlementInfoConfirm, nRequestID):
        """ReqSettlementInfoConfirm method"""
        return _ctp.CThostFtdcTraderApi_ReqSettlementInfoConfirm(
            self, pSettlementInfoConfirm, nRequestID
        )

    def ReqRemoveParkedOrder(self, pRemoveParkedOrder, nRequestID):
        """ReqRemoveParkedOrder method"""
        return _ctp.CThostFtdcTraderApi_ReqRemoveParkedOrder(
            self, pRemoveParkedOrder, nRequestID
        )

    def ReqRemoveParkedOrderAction(self, pRemoveParkedOrderAction, nRequestID):
        """ReqRemoveParkedOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqRemoveParkedOrderAction(
            self, pRemoveParkedOrderAction, nRequestID
        )

    def ReqExecOrderInsert(self, pInputExecOrder, nRequestID):
        """ReqExecOrderInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqExecOrderInsert(
            self, pInputExecOrder, nRequestID
        )

    def ReqExecOrderAction(self, pInputExecOrderAction, nRequestID):
        """ReqExecOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqExecOrderAction(
            self, pInputExecOrderAction, nRequestID
        )

    def ReqForQuoteInsert(self, pInputForQuote, nRequestID):
        """ReqForQuoteInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqForQuoteInsert(
            self, pInputForQuote, nRequestID
        )

    def ReqQuoteInsert(self, pInputQuote, nRequestID):
        """ReqQuoteInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqQuoteInsert(self, pInputQuote, nRequestID)

    def ReqQuoteAction(self, pInputQuoteAction, nRequestID):
        """ReqQuoteAction method"""
        return _ctp.CThostFtdcTraderApi_ReqQuoteAction(
            self, pInputQuoteAction, nRequestID
        )

    def ReqBatchOrderAction(self, pInputBatchOrderAction, nRequestID):
        """ReqBatchOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqBatchOrderAction(
            self, pInputBatchOrderAction, nRequestID
        )

    def ReqOptionSelfCloseInsert(self, pInputOptionSelfClose, nRequestID):
        """ReqOptionSelfCloseInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqOptionSelfCloseInsert(
            self, pInputOptionSelfClose, nRequestID
        )

    def ReqOptionSelfCloseAction(self, pInputOptionSelfCloseAction, nRequestID):
        """ReqOptionSelfCloseAction method"""
        return _ctp.CThostFtdcTraderApi_ReqOptionSelfCloseAction(
            self, pInputOptionSelfCloseAction, nRequestID
        )

    def ReqCombActionInsert(self, pInputCombAction, nRequestID):
        """ReqCombActionInsert method"""
        return _ctp.CThostFtdcTraderApi_ReqCombActionInsert(
            self, pInputCombAction, nRequestID
        )

    def ReqQryOrder(self, pQryOrder, nRequestID):
        """ReqQryOrder method"""
        return _ctp.CThostFtdcTraderApi_ReqQryOrder(self, pQryOrder, nRequestID)

    def ReqQryTrade(self, pQryTrade, nRequestID):
        """ReqQryTrade method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTrade(self, pQryTrade, nRequestID)

    def ReqQryInvestorPosition(self, pQryInvestorPosition, nRequestID):
        """ReqQryInvestorPosition method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorPosition(
            self, pQryInvestorPosition, nRequestID
        )

    def ReqQryTradingAccount(self, pQryTradingAccount, nRequestID):
        """ReqQryTradingAccount method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTradingAccount(
            self, pQryTradingAccount, nRequestID
        )

    def ReqQryInvestor(self, pQryInvestor, nRequestID):
        """ReqQryInvestor method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestor(self, pQryInvestor, nRequestID)

    def ReqQryTradingCode(self, pQryTradingCode, nRequestID):
        """ReqQryTradingCode method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTradingCode(
            self, pQryTradingCode, nRequestID
        )

    def ReqQryInstrumentMarginRate(self, pQryInstrumentMarginRate, nRequestID):
        """ReqQryInstrumentMarginRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInstrumentMarginRate(
            self, pQryInstrumentMarginRate, nRequestID
        )

    def ReqQryInstrumentCommissionRate(self, pQryInstrumentCommissionRate, nRequestID):
        """ReqQryInstrumentCommissionRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInstrumentCommissionRate(
            self, pQryInstrumentCommissionRate, nRequestID
        )

    def ReqQryExchange(self, pQryExchange, nRequestID):
        """ReqQryExchange method"""
        return _ctp.CThostFtdcTraderApi_ReqQryExchange(self, pQryExchange, nRequestID)

    def ReqQryProduct(self, pQryProduct, nRequestID):
        """ReqQryProduct method"""
        return _ctp.CThostFtdcTraderApi_ReqQryProduct(self, pQryProduct, nRequestID)

    def ReqQryInstrument(self, pQryInstrument, nRequestID):
        """ReqQryInstrument method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInstrument(
            self, pQryInstrument, nRequestID
        )

    def ReqQryDepthMarketData(self, pQryDepthMarketData, nRequestID):
        """ReqQryDepthMarketData method"""
        return _ctp.CThostFtdcTraderApi_ReqQryDepthMarketData(
            self, pQryDepthMarketData, nRequestID
        )

    def ReqQryTraderOffer(self, pQryTraderOffer, nRequestID):
        """ReqQryTraderOffer method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTraderOffer(
            self, pQryTraderOffer, nRequestID
        )

    def ReqQrySettlementInfo(self, pQrySettlementInfo, nRequestID):
        """ReqQrySettlementInfo method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySettlementInfo(
            self, pQrySettlementInfo, nRequestID
        )

    def ReqQryTransferBank(self, pQryTransferBank, nRequestID):
        """ReqQryTransferBank method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTransferBank(
            self, pQryTransferBank, nRequestID
        )

    def ReqQryInvestorPositionDetail(self, pQryInvestorPositionDetail, nRequestID):
        """ReqQryInvestorPositionDetail method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorPositionDetail(
            self, pQryInvestorPositionDetail, nRequestID
        )

    def ReqQryNotice(self, pQryNotice, nRequestID):
        """ReqQryNotice method"""
        return _ctp.CThostFtdcTraderApi_ReqQryNotice(self, pQryNotice, nRequestID)

    def ReqQrySettlementInfoConfirm(self, pQrySettlementInfoConfirm, nRequestID):
        """ReqQrySettlementInfoConfirm method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySettlementInfoConfirm(
            self, pQrySettlementInfoConfirm, nRequestID
        )

    def ReqQryInvestorPositionCombineDetail(
        self, pQryInvestorPositionCombineDetail, nRequestID
    ):
        """ReqQryInvestorPositionCombineDetail method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorPositionCombineDetail(
            self, pQryInvestorPositionCombineDetail, nRequestID
        )

    def ReqQryCFMMCTradingAccountKey(self, pQryCFMMCTradingAccountKey, nRequestID):
        """ReqQryCFMMCTradingAccountKey method"""
        return _ctp.CThostFtdcTraderApi_ReqQryCFMMCTradingAccountKey(
            self, pQryCFMMCTradingAccountKey, nRequestID
        )

    def ReqQryEWarrantOffset(self, pQryEWarrantOffset, nRequestID):
        """ReqQryEWarrantOffset method"""
        return _ctp.CThostFtdcTraderApi_ReqQryEWarrantOffset(
            self, pQryEWarrantOffset, nRequestID
        )

    def ReqQryInvestorProductGroupMargin(
        self, pQryInvestorProductGroupMargin, nRequestID
    ):
        """ReqQryInvestorProductGroupMargin method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorProductGroupMargin(
            self, pQryInvestorProductGroupMargin, nRequestID
        )

    def ReqQryExchangeMarginRate(self, pQryExchangeMarginRate, nRequestID):
        """ReqQryExchangeMarginRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryExchangeMarginRate(
            self, pQryExchangeMarginRate, nRequestID
        )

    def ReqQryExchangeMarginRateAdjust(self, pQryExchangeMarginRateAdjust, nRequestID):
        """ReqQryExchangeMarginRateAdjust method"""
        return _ctp.CThostFtdcTraderApi_ReqQryExchangeMarginRateAdjust(
            self, pQryExchangeMarginRateAdjust, nRequestID
        )

    def ReqQryExchangeRate(self, pQryExchangeRate, nRequestID):
        """ReqQryExchangeRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryExchangeRate(
            self, pQryExchangeRate, nRequestID
        )

    def ReqQrySecAgentACIDMap(self, pQrySecAgentACIDMap, nRequestID):
        """ReqQrySecAgentACIDMap method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySecAgentACIDMap(
            self, pQrySecAgentACIDMap, nRequestID
        )

    def ReqQryProductExchRate(self, pQryProductExchRate, nRequestID):
        """ReqQryProductExchRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryProductExchRate(
            self, pQryProductExchRate, nRequestID
        )

    def ReqQryProductGroup(self, pQryProductGroup, nRequestID):
        """ReqQryProductGroup method"""
        return _ctp.CThostFtdcTraderApi_ReqQryProductGroup(
            self, pQryProductGroup, nRequestID
        )

    def ReqQryMMInstrumentCommissionRate(
        self, pQryMMInstrumentCommissionRate, nRequestID
    ):
        """ReqQryMMInstrumentCommissionRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryMMInstrumentCommissionRate(
            self, pQryMMInstrumentCommissionRate, nRequestID
        )

    def ReqQryMMOptionInstrCommRate(self, pQryMMOptionInstrCommRate, nRequestID):
        """ReqQryMMOptionInstrCommRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryMMOptionInstrCommRate(
            self, pQryMMOptionInstrCommRate, nRequestID
        )

    def ReqQryInstrumentOrderCommRate(self, pQryInstrumentOrderCommRate, nRequestID):
        """ReqQryInstrumentOrderCommRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInstrumentOrderCommRate(
            self, pQryInstrumentOrderCommRate, nRequestID
        )

    def ReqQrySecAgentTradingAccount(self, pQryTradingAccount, nRequestID):
        """ReqQrySecAgentTradingAccount method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySecAgentTradingAccount(
            self, pQryTradingAccount, nRequestID
        )

    def ReqQrySecAgentCheckMode(self, pQrySecAgentCheckMode, nRequestID):
        """ReqQrySecAgentCheckMode method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySecAgentCheckMode(
            self, pQrySecAgentCheckMode, nRequestID
        )

    def ReqQrySecAgentTradeInfo(self, pQrySecAgentTradeInfo, nRequestID):
        """ReqQrySecAgentTradeInfo method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySecAgentTradeInfo(
            self, pQrySecAgentTradeInfo, nRequestID
        )

    def ReqQryOptionInstrTradeCost(self, pQryOptionInstrTradeCost, nRequestID):
        """ReqQryOptionInstrTradeCost method"""
        return _ctp.CThostFtdcTraderApi_ReqQryOptionInstrTradeCost(
            self, pQryOptionInstrTradeCost, nRequestID
        )

    def ReqQryOptionInstrCommRate(self, pQryOptionInstrCommRate, nRequestID):
        """ReqQryOptionInstrCommRate method"""
        return _ctp.CThostFtdcTraderApi_ReqQryOptionInstrCommRate(
            self, pQryOptionInstrCommRate, nRequestID
        )

    def ReqQryExecOrder(self, pQryExecOrder, nRequestID):
        """ReqQryExecOrder method"""
        return _ctp.CThostFtdcTraderApi_ReqQryExecOrder(self, pQryExecOrder, nRequestID)

    def ReqQryForQuote(self, pQryForQuote, nRequestID):
        """ReqQryForQuote method"""
        return _ctp.CThostFtdcTraderApi_ReqQryForQuote(self, pQryForQuote, nRequestID)

    def ReqQryQuote(self, pQryQuote, nRequestID):
        """ReqQryQuote method"""
        return _ctp.CThostFtdcTraderApi_ReqQryQuote(self, pQryQuote, nRequestID)

    def ReqQryOptionSelfClose(self, pQryOptionSelfClose, nRequestID):
        """ReqQryOptionSelfClose method"""
        return _ctp.CThostFtdcTraderApi_ReqQryOptionSelfClose(
            self, pQryOptionSelfClose, nRequestID
        )

    def ReqQryInvestUnit(self, pQryInvestUnit, nRequestID):
        """ReqQryInvestUnit method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestUnit(
            self, pQryInvestUnit, nRequestID
        )

    def ReqQryCombInstrumentGuard(self, pQryCombInstrumentGuard, nRequestID):
        """ReqQryCombInstrumentGuard method"""
        return _ctp.CThostFtdcTraderApi_ReqQryCombInstrumentGuard(
            self, pQryCombInstrumentGuard, nRequestID
        )

    def ReqQryCombAction(self, pQryCombAction, nRequestID):
        """ReqQryCombAction method"""
        return _ctp.CThostFtdcTraderApi_ReqQryCombAction(
            self, pQryCombAction, nRequestID
        )

    def ReqQryTransferSerial(self, pQryTransferSerial, nRequestID):
        """ReqQryTransferSerial method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTransferSerial(
            self, pQryTransferSerial, nRequestID
        )

    def ReqQryAccountregister(self, pQryAccountregister, nRequestID):
        """ReqQryAccountregister method"""
        return _ctp.CThostFtdcTraderApi_ReqQryAccountregister(
            self, pQryAccountregister, nRequestID
        )

    def ReqQryContractBank(self, pQryContractBank, nRequestID):
        """ReqQryContractBank method"""
        return _ctp.CThostFtdcTraderApi_ReqQryContractBank(
            self, pQryContractBank, nRequestID
        )

    def ReqQryParkedOrder(self, pQryParkedOrder, nRequestID):
        """ReqQryParkedOrder method"""
        return _ctp.CThostFtdcTraderApi_ReqQryParkedOrder(
            self, pQryParkedOrder, nRequestID
        )

    def ReqQryParkedOrderAction(self, pQryParkedOrderAction, nRequestID):
        """ReqQryParkedOrderAction method"""
        return _ctp.CThostFtdcTraderApi_ReqQryParkedOrderAction(
            self, pQryParkedOrderAction, nRequestID
        )

    def ReqQryTradingNotice(self, pQryTradingNotice, nRequestID):
        """ReqQryTradingNotice method"""
        return _ctp.CThostFtdcTraderApi_ReqQryTradingNotice(
            self, pQryTradingNotice, nRequestID
        )

    def ReqQryBrokerTradingParams(self, pQryBrokerTradingParams, nRequestID):
        """ReqQryBrokerTradingParams method"""
        return _ctp.CThostFtdcTraderApi_ReqQryBrokerTradingParams(
            self, pQryBrokerTradingParams, nRequestID
        )

    def ReqQryBrokerTradingAlgos(self, pQryBrokerTradingAlgos, nRequestID):
        """ReqQryBrokerTradingAlgos method"""
        return _ctp.CThostFtdcTraderApi_ReqQryBrokerTradingAlgos(
            self, pQryBrokerTradingAlgos, nRequestID
        )

    def ReqQueryCFMMCTradingAccountToken(
        self, pQueryCFMMCTradingAccountToken, nRequestID
    ):
        """ReqQueryCFMMCTradingAccountToken method"""
        return _ctp.CThostFtdcTraderApi_ReqQueryCFMMCTradingAccountToken(
            self, pQueryCFMMCTradingAccountToken, nRequestID
        )

    def ReqFromBankToFutureByFuture(self, pReqTransfer, nRequestID):
        """ReqFromBankToFutureByFuture method"""
        return _ctp.CThostFtdcTraderApi_ReqFromBankToFutureByFuture(
            self, pReqTransfer, nRequestID
        )

    def ReqFromFutureToBankByFuture(self, pReqTransfer, nRequestID):
        """ReqFromFutureToBankByFuture method"""
        return _ctp.CThostFtdcTraderApi_ReqFromFutureToBankByFuture(
            self, pReqTransfer, nRequestID
        )

    def ReqQueryBankAccountMoneyByFuture(self, pReqQueryAccount, nRequestID):
        """ReqQueryBankAccountMoneyByFuture method"""
        return _ctp.CThostFtdcTraderApi_ReqQueryBankAccountMoneyByFuture(
            self, pReqQueryAccount, nRequestID
        )

    def ReqQryClassifiedInstrument(self, pQryClassifiedInstrument, nRequestID):
        """ReqQryClassifiedInstrument method"""
        return _ctp.CThostFtdcTraderApi_ReqQryClassifiedInstrument(
            self, pQryClassifiedInstrument, nRequestID
        )

    def ReqQryCombPromotionParam(self, pQryCombPromotionParam, nRequestID):
        """ReqQryCombPromotionParam method"""
        return _ctp.CThostFtdcTraderApi_ReqQryCombPromotionParam(
            self, pQryCombPromotionParam, nRequestID
        )

    def ReqQryRiskSettleInvstPosition(self, pQryRiskSettleInvstPosition, nRequestID):
        """ReqQryRiskSettleInvstPosition method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRiskSettleInvstPosition(
            self, pQryRiskSettleInvstPosition, nRequestID
        )

    def ReqQryRiskSettleProductStatus(self, pQryRiskSettleProductStatus, nRequestID):
        """ReqQryRiskSettleProductStatus method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRiskSettleProductStatus(
            self, pQryRiskSettleProductStatus, nRequestID
        )

    def ReqQrySPBMFutureParameter(self, pQrySPBMFutureParameter, nRequestID):
        """ReqQrySPBMFutureParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMFutureParameter(
            self, pQrySPBMFutureParameter, nRequestID
        )

    def ReqQrySPBMOptionParameter(self, pQrySPBMOptionParameter, nRequestID):
        """ReqQrySPBMOptionParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMOptionParameter(
            self, pQrySPBMOptionParameter, nRequestID
        )

    def ReqQrySPBMIntraParameter(self, pQrySPBMIntraParameter, nRequestID):
        """ReqQrySPBMIntraParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMIntraParameter(
            self, pQrySPBMIntraParameter, nRequestID
        )

    def ReqQrySPBMInterParameter(self, pQrySPBMInterParameter, nRequestID):
        """ReqQrySPBMInterParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMInterParameter(
            self, pQrySPBMInterParameter, nRequestID
        )

    def ReqQrySPBMPortfDefinition(self, pQrySPBMPortfDefinition, nRequestID):
        """ReqQrySPBMPortfDefinition method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMPortfDefinition(
            self, pQrySPBMPortfDefinition, nRequestID
        )

    def ReqQrySPBMInvestorPortfDef(self, pQrySPBMInvestorPortfDef, nRequestID):
        """ReqQrySPBMInvestorPortfDef method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMInvestorPortfDef(
            self, pQrySPBMInvestorPortfDef, nRequestID
        )

    def ReqQryInvestorPortfMarginRatio(self, pQryInvestorPortfMarginRatio, nRequestID):
        """ReqQryInvestorPortfMarginRatio method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorPortfMarginRatio(
            self, pQryInvestorPortfMarginRatio, nRequestID
        )

    def ReqQryInvestorProdSPBMDetail(self, pQryInvestorProdSPBMDetail, nRequestID):
        """ReqQryInvestorProdSPBMDetail method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorProdSPBMDetail(
            self, pQryInvestorProdSPBMDetail, nRequestID
        )

    def ReqQryInvestorCommoditySPMMMargin(
        self, pQryInvestorCommoditySPMMMargin, nRequestID
    ):
        """ReqQryInvestorCommoditySPMMMargin method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorCommoditySPMMMargin(
            self, pQryInvestorCommoditySPMMMargin, nRequestID
        )

    def ReqQryInvestorCommodityGroupSPMMMargin(
        self, pQryInvestorCommodityGroupSPMMMargin, nRequestID
    ):
        """ReqQryInvestorCommodityGroupSPMMMargin method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorCommodityGroupSPMMMargin(
            self, pQryInvestorCommodityGroupSPMMMargin, nRequestID
        )

    def ReqQrySPMMInstParam(self, pQrySPMMInstParam, nRequestID):
        """ReqQrySPMMInstParam method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPMMInstParam(
            self, pQrySPMMInstParam, nRequestID
        )

    def ReqQrySPMMProductParam(self, pQrySPMMProductParam, nRequestID):
        """ReqQrySPMMProductParam method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPMMProductParam(
            self, pQrySPMMProductParam, nRequestID
        )

    def ReqQrySPBMAddOnInterParameter(self, pQrySPBMAddOnInterParameter, nRequestID):
        """ReqQrySPBMAddOnInterParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQrySPBMAddOnInterParameter(
            self, pQrySPBMAddOnInterParameter, nRequestID
        )

    def ReqQryRCAMSCombProductInfo(self, pQryRCAMSCombProductInfo, nRequestID):
        """ReqQryRCAMSCombProductInfo method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSCombProductInfo(
            self, pQryRCAMSCombProductInfo, nRequestID
        )

    def ReqQryRCAMSInstrParameter(self, pQryRCAMSInstrParameter, nRequestID):
        """ReqQryRCAMSInstrParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSInstrParameter(
            self, pQryRCAMSInstrParameter, nRequestID
        )

    def ReqQryRCAMSIntraParameter(self, pQryRCAMSIntraParameter, nRequestID):
        """ReqQryRCAMSIntraParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSIntraParameter(
            self, pQryRCAMSIntraParameter, nRequestID
        )

    def ReqQryRCAMSInterParameter(self, pQryRCAMSInterParameter, nRequestID):
        """ReqQryRCAMSInterParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSInterParameter(
            self, pQryRCAMSInterParameter, nRequestID
        )

    def ReqQryRCAMSShortOptAdjustParam(self, pQryRCAMSShortOptAdjustParam, nRequestID):
        """ReqQryRCAMSShortOptAdjustParam method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSShortOptAdjustParam(
            self, pQryRCAMSShortOptAdjustParam, nRequestID
        )

    def ReqQryRCAMSInvestorCombPosition(
        self, pQryRCAMSInvestorCombPosition, nRequestID
    ):
        """ReqQryRCAMSInvestorCombPosition method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRCAMSInvestorCombPosition(
            self, pQryRCAMSInvestorCombPosition, nRequestID
        )

    def ReqQryInvestorProdRCAMSMargin(self, pQryInvestorProdRCAMSMargin, nRequestID):
        """ReqQryInvestorProdRCAMSMargin method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorProdRCAMSMargin(
            self, pQryInvestorProdRCAMSMargin, nRequestID
        )

    def ReqQryRULEInstrParameter(self, pQryRULEInstrParameter, nRequestID):
        """ReqQryRULEInstrParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRULEInstrParameter(
            self, pQryRULEInstrParameter, nRequestID
        )

    def ReqQryRULEIntraParameter(self, pQryRULEIntraParameter, nRequestID):
        """ReqQryRULEIntraParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRULEIntraParameter(
            self, pQryRULEIntraParameter, nRequestID
        )

    def ReqQryRULEInterParameter(self, pQryRULEInterParameter, nRequestID):
        """ReqQryRULEInterParameter method"""
        return _ctp.CThostFtdcTraderApi_ReqQryRULEInterParameter(
            self, pQryRULEInterParameter, nRequestID
        )

    def ReqQryInvestorProdRULEMargin(self, pQryInvestorProdRULEMargin, nRequestID):
        """ReqQryInvestorProdRULEMargin method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorProdRULEMargin(
            self, pQryInvestorProdRULEMargin, nRequestID
        )

    def ReqQryInvestorPortfSetting(self, pQryInvestorPortfSetting, nRequestID):
        """ReqQryInvestorPortfSetting method"""
        return _ctp.CThostFtdcTraderApi_ReqQryInvestorPortfSetting(
            self, pQryInvestorPortfSetting, nRequestID
        )


# Register CThostFtdcTraderApi in _ctp:
_ctp.CThostFtdcTraderApi_swigregister(CThostFtdcTraderApi)


__all__ = [
    'CThostFtdcTraderSpi',
    'CThostFtdcTraderApi',
]
