# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP  API (CThostFtdcMdSpi / CThostFtdcMdApi)"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr, print_exception, stderr, weakref


class CThostFtdcMdSpi:
    """Class CThostFtdcMdSpi"""

    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag'
    )
    __repr__ = _swig_repr

    def OnFrontConnected(self):
        """OnFrontConnected method"""
        return _ctp.CThostFtdcMdSpi_OnFrontConnected(self)

    def OnFrontDisconnected(self, nReason):
        """OnFrontDisconnected method"""
        return _ctp.CThostFtdcMdSpi_OnFrontDisconnected(self, nReason)

    def OnHeartBeatWarning(self, nTimeLapse):
        """OnHeartBeatWarning method"""
        return _ctp.CThostFtdcMdSpi_OnHeartBeatWarning(self, nTimeLapse)

    def OnRspUserLogin(self, pRspUserLogin, pRspInfo, nRequestID, bIsLast):
        """OnRspUserLogin method"""
        return _ctp.CThostFtdcMdSpi_OnRspUserLogin(
            self, pRspUserLogin, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUserLogout(self, pUserLogout, pRspInfo, nRequestID, bIsLast):
        """OnRspUserLogout method"""
        return _ctp.CThostFtdcMdSpi_OnRspUserLogout(
            self, pUserLogout, pRspInfo, nRequestID, bIsLast
        )

    def OnRspQryMulticastInstrument(self, pMulticastInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspQryMulticastInstrument method"""
        return _ctp.CThostFtdcMdSpi_OnRspQryMulticastInstrument(
            self, pMulticastInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspError(self, pRspInfo, nRequestID, bIsLast):
        """OnRspError method"""
        return _ctp.CThostFtdcMdSpi_OnRspError(self, pRspInfo, nRequestID, bIsLast)

    def OnRspSubMarketData(self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspSubMarketData method"""
        return _ctp.CThostFtdcMdSpi_OnRspSubMarketData(
            self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUnSubMarketData(self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspUnSubMarketData method"""
        return _ctp.CThostFtdcMdSpi_OnRspUnSubMarketData(
            self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspSubForQuoteRsp(self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspSubForQuoteRsp method"""
        return _ctp.CThostFtdcMdSpi_OnRspSubForQuoteRsp(
            self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRspUnSubForQuoteRsp(self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast):
        """OnRspUnSubForQuoteRsp method"""
        return _ctp.CThostFtdcMdSpi_OnRspUnSubForQuoteRsp(
            self, pSpecificInstrument, pRspInfo, nRequestID, bIsLast
        )

    def OnRtnDepthMarketData(self, pDepthMarketData):
        """OnRtnDepthMarketData method"""
        return _ctp.CThostFtdcMdSpi_OnRtnDepthMarketData(self, pDepthMarketData)

    def OnRtnForQuoteRsp(self, pForQuoteRsp):
        """OnRtnForQuoteRsp method"""
        return _ctp.CThostFtdcMdSpi_OnRtnForQuoteRsp(self, pForQuoteRsp)

    def pyError(self, type, value, traceback):
        """Handles an error thrown during invocation of an method.

        Arguments are those provided by sys.exc_info()
        """
        stderr.write('Exception thrown during method dispatch:\n')
        print_exception(type, value, traceback)

    def __init__(self):
        """__init__ method"""
        _self = None if self.__class__ == CThostFtdcMdSpi else self
        _ctp.CThostFtdcMdSpi_swiginit(
            self,
            _ctp.new_CThostFtdcMdSpi(
                _self,
            ),
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMdSpi

    def __disown__(self):
        self.this.disown()
        _ctp.disown_CThostFtdcMdSpi(self)
        return weakref.proxy(self)


# Register CThostFtdcMdSpi in _ctp:
_ctp.CThostFtdcMdSpi_swigregister(CThostFtdcMdSpi)


class CThostFtdcMdApi:
    """Class CThostFtdcMdApi"""

    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag'
    )

    def __init__(self, *args, **kwargs):
        """__init__ method"""
        raise AttributeError('No constructor defined - class is abstract')

    __repr__ = _swig_repr

    @staticmethod
    def CreateFtdcMdApi(*args):
        """CreateFtdcMdApi method"""
        return _ctp.CThostFtdcMdApi_CreateFtdcMdApi(*args)

    @staticmethod
    def GetApiVersion():
        """GetApiVersion method"""
        return _ctp.CThostFtdcMdApi_GetApiVersion()

    def Release(self):
        """Release method"""
        return _ctp.CThostFtdcMdApi_Release(self)

    def Init(self):
        """Init method"""
        return _ctp.CThostFtdcMdApi_Init(self)

    def Join(self):
        """Join method"""
        return _ctp.CThostFtdcMdApi_Join(self)

    def GetTradingDay(self):
        """GetTradingDay method"""
        return _ctp.CThostFtdcMdApi_GetTradingDay(self)

    def RegisterFront(self, pszFrontAddress):
        """RegisterFront method"""
        return _ctp.CThostFtdcMdApi_RegisterFront(self, pszFrontAddress)

    def RegisterNameServer(self, pszNsAddress):
        """RegisterNameServer method"""
        return _ctp.CThostFtdcMdApi_RegisterNameServer(self, pszNsAddress)

    def RegisterFensUserInfo(self, pFensUserInfo):
        """RegisterFensUserInfo method"""
        return _ctp.CThostFtdcMdApi_RegisterFensUserInfo(self, pFensUserInfo)

    def RegisterSpi(self, pSpi):
        """RegisterSpi method"""
        return _ctp.CThostFtdcMdApi_RegisterSpi(self, pSpi)

    def SubscribeMarketData(self, ppInstrumentID):
        """SubscribeMarketData method"""
        return _ctp.CThostFtdcMdApi_SubscribeMarketData(self, ppInstrumentID)

    def UnSubscribeMarketData(self, ppInstrumentID):
        """UnSubscribeMarketData method"""
        return _ctp.CThostFtdcMdApi_UnSubscribeMarketData(self, ppInstrumentID)

    def SubscribeForQuoteRsp(self, ppInstrumentID):
        """SubscribeForQuoteRsp method"""
        return _ctp.CThostFtdcMdApi_SubscribeForQuoteRsp(self, ppInstrumentID)

    def UnSubscribeForQuoteRsp(self, ppInstrumentID):
        """UnSubscribeForQuoteRsp method"""
        return _ctp.CThostFtdcMdApi_UnSubscribeForQuoteRsp(self, ppInstrumentID)

    def ReqUserLogin(self, pReqUserLoginField, nRequestID):
        """ReqUserLogin method"""
        return _ctp.CThostFtdcMdApi_ReqUserLogin(self, pReqUserLoginField, nRequestID)

    def ReqUserLogout(self, pUserLogout, nRequestID):
        """ReqUserLogout method"""
        return _ctp.CThostFtdcMdApi_ReqUserLogout(self, pUserLogout, nRequestID)

    def ReqQryMulticastInstrument(self, pQryMulticastInstrument, nRequestID):
        """ReqQryMulticastInstrument method"""
        return _ctp.CThostFtdcMdApi_ReqQryMulticastInstrument(
            self, pQryMulticastInstrument, nRequestID
        )


# Register CThostFtdcMdApi in _ctp:
_ctp.CThostFtdcMdApi_swigregister(CThostFtdcMdApi)

__all__ = [
    'CThostFtdcMdSpi',
    'CThostFtdcMdApi',
]
